import { ISuggestion } from "./types";
import { IFilm } from "./types";

export const suggestions: ISuggestion[] = [
   {
      title: "See again",
      films: [
         {
            id: "again1",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/again/1.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "again2",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/again/2.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "again3",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/again/3.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "again4",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/again/4.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "again5",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/again/5.jpg",
            match: "89%",
            label: "/names/1.png",
         },
      ],
   },
   {
      title: "Top 10 in your country",
      type: "numbered",
      films: [
         {
            id: "top1",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/top/1.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "top2",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/top/2.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "top3",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/top/3.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "top4",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/top/4.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "top5",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/top/5.jpg",
            match: "89%",
            label: "/names/1.png",
         },
      ],
   },
   {
      title: "Trending Now",
      films: [
         {
            id: "trending1",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/trending/1.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "trending2",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/trending/2.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "trending3",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/trending/3.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "trending4",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/trending/4.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "trending5",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/trending/5.jpg",
            match: "89%",
            label: "/names/1.png",
         },
      ],
   },
   {
      title: "Sci-fi shows",
      films: [
         {
            id: "sciFi1",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/sciFi/1.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "sciFi2",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/sciFi/2.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "sciFi3",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/sciFi/3.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "sciFi4",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/sciFi/4.jpg",
            match: "89%",
            label: "/names/1.png",
         },
         {
            id: "sciFi5",
            name: "Test",
            type: "serial",
            rating: 4,
            year: 2010,
            ageRestriction: "+16",
            genre: ["horror"],
            season: 10,
            subName: "Lines we cross",
            duration: "50m",
            description:
               "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
            poster: "/images/posters/2.jpg",
            image: "/images/sciFi/5.jpg",
            match: "89%",
            label: "/names/1.png",
         },
      ],
   },
];

export const filmPoster: IFilm = {
   id: "currentPoster",
   name: "Maid",
   type: "serial",
   rating: 4,
   year: 2010,
   ageRestriction: "+16",
   genre: ["horror"],
   season: 1,
   subName: "Lines we cross",
   duration: "50m",
   description:
      "We pick back up with the group in Oceanside continuing to train in case the Whisperers return. Tensions are high as our heroes struggle to hold onto their concept of civilization.",
   poster: "/images/posters/1.jpg",
   image: "/images/posters/1.jpg",
   match: "89%",
   label: "/names/1.png",
};
